# Site settings
title: Booles' Rings
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Researchers. Connecting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://boolesrings.org" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
